name: RemoveEnchantments
version: 1.0
authors: [Justin Brubaker,JustBru00]
main: com.gmail.justbru00.removeenchantments.Main
commands:
  removeenchantments:
    description: Removes all enchantments.
    aliases: [removeench]